module.exports = {
  authController: require("./auth.controller"),
  companyUsersController: require("./company-users.controller"),
  filtersController: require("./filters.controller"),
  configurationsController: require("./configurations.controller"),
  webhooksController: require("./webhooks.controller"),
  campaignsController: require("./campaign.controller"),
  campaignsRunController: require("./campaigns-run.controller"),
  segmentsController: require("./segments.controller"),
  templatesController: require("./templates.controller"),
  usersController: require("./users.controller"),
  accessTokensController: require("./access-tokens.controller"),
  rolesController: require("./roles.controller"),
  stripeController: require("./stripe.controller"),
  socialLinksController: require("./social-links.controller"),
  assetsController: require("./assetsController"),
};
