module.exports = {
  authController: require("./auth.controller"),
  companyContactsController: require("./company-contacts.controller"),
  filtersController: require("./filters.controller"),
  configurationsController: require("./configurations.controller"),
  webhooksController: require("./webhooks.controller"),
  campaignsController: require("./campaign.controller"),
  campaignsRunController: require("./campaigns-run.controller"),
  segmentsController: require("./segments.controller"),
  templatesController: require("./templates.controller"),
  templateCategoriesController: require("./template-categories.controller"),
  usersController: require("./users.controller"),
  accessTokensController: require("./access-tokens.controller"),
  rolesController: require("./roles.controller"),
  stripeController: require("./stripe.controller"),
  socialLinksController: require("./social-links.controller"),
  assetsController: require("./assets.controller"),
  emailsSentController: require("./emails-sent.controller"),
  rewardsController: require("./rewards.controller"),
  overageConsumptionController: require("./overage-consumption.controller"),
  companiesController: require("./companies.controller"),
  topupController: require("./topup.controller"),
  plansController: require("./plans.controller"),
};
