module.exports = {
  User: require("./user.model"),
  Filter: require("./filter.model"),
  CompanyContact: require("./company-contact.model"),
  Configuration: require("./configuration.model"),
  Campaign: require("./campaign.model"),
  CampaignRun: require("./campaign-run.model"),
  Segment: require("./segment.model"),
  Template: require("./template.model"),
  Cron: require("./cron.model"),
  Company: require("./company.model"),
  AccessToken: require("./access-token.model"),
  Role: require("./role.model"),
  SocialLink: require("./social-link.model"),
  Asset: require("./assets.model"),
  EmailSent: require("./emails-sent.model"),
  ReferralCode: require("./referral-code.model"),
  Reward: require("./reward.model"),
  Plan: require("./plan.model"),
  TemplateCategory: require("./template-category.model"),
  OverageConsumption: require("./overage-consumption.model"),
  Topup: require("./topup.model"),
};
