module.exports = {
  User: require("./user.model"),
  Filter: require("./filter.model"),
  CompanyUser: require("./company-user.model"),
  Configuration: require("./configuration.model"),
  Campaign: require("./campaign.model"),
  Segment: require("./segment.model"),
  Template: require("./template.model"),
  Cron: require("./cron.model"),
  Company: require("./company.model"),
  AccessToken: require("./access-token.model"),
  Role: require("./role.model"),
  SocialLink: require("./social-link.model"),
  Asset: require("./assets.model"),
  EmailSent: require("./emails-sent.model"),
  RefreshToken: require("./refresh-token.model"),
};
